// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hglotfvukqlbjkolibrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhnbG90ZnZ1a3FsYmprb2xpYnJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3ODYxODcsImV4cCI6MjA2NDM2MjE4N30.hZTtUivVi8PRtgRSRmvwHHaz5nxMJaYN6srntc5YYko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);